### ISSUE TITLE
Is it possible to output the bitmap to fb0?

### ISSUE THREAD

**Issue by iAmInActions** [gameblabla/mccraft#1]
Hello,
I have seen this and was thinking about if it would be possible to output the render to /dev/fb0 to make it work on unix systems or nintendo consoles (I personally am planing to make it work on the 3ds). I have experimented a bit but I'm not good at C so I have not gotten it to work yet.

**Comment by gameblabla** [comment]
I'm working on it and SDL support. It already works in my private branch but speed is not ideal due to how the textures were made so it will require some reworking but it should be easy enough.
As for fbdev support, it should be trivial to add once done. the only issue is that we would have to actually complete the game and add controls.

**Comment by gameblabla** [comment]
There's some basic fbdev code in there but it only supports 16bpp and it is untested.
I don't intend to support the fbdev backend so it is just provided for reference.
